# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-translate-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26.4'

    # - name: Build Extractor/Injector Linux
    #   run: go build -v ./cmd/translate
    #   env:
    #     GOARCH: amd64
    #     GOOS: linux

    - name: Build Extractor/Injector Windows
      run: go build -v ./cmd/translate
      env:
        GOARCH: amd64
        GOOS: windows

    - name: Upload to GitHub
      uses: actions/upload-artifact@v7
      with:
        path: "translate.exe"
        archive: false
        if-no-files-found: error
      
    # - name: Build Codec Linux
    #   run: go build -v ./cmd/codec
    #   env:
    #     GOARCH: amd64
    #     GOOS: linux

    # - name: Build Codec Windows
    #   run: go build -v ./cmd/codec
    #   env:
    #     GOARCH: amd64
    #     GOOS: windows

    # - name: Test
    #   run: go test -v ./...
    #
    #
    
  create-release:
    name: Create Release
    needs: [build-translate-windows]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts/
          merge-multiple: true
          skip-decompress: true

      - name: Display Downloaded Artifacts
        run: find ./artifacts/ -type f | sort

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Rolling Release"
          files: |
            ./artifacts/translate.exe
