# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-translate-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26.4'

    # - name: Build Extractor/Injector Linux
    #   run: go build -v ./cmd/translate
    #   env:
    #     GOARCH: amd64
    #     GOOS: linux

    - name: Upload to GitHub
      uses: actions/upload-artifact@v7
      with:
        path: "translate.exe"
        archive: false
        if-no-files-found: error
      
    - name: Build Extractor/Injector Windows
      run: go build -v ./cmd/translate
      env:
        GOARCH: amd64
        GOOS: windows

    # - name: Build Codec Linux
    #   run: go build -v ./cmd/codec
    #   env:
    #     GOARCH: amd64
    #     GOOS: linux

    # - name: Build Codec Windows
    #   run: go build -v ./cmd/codec
    #   env:
    #     GOARCH: amd64
    #     GOOS: windows

    # - name: Test
    #   run: go test -v ./...
